import { Token, Message } from './types';

export const mockToken: Token = {
  name: "Trencher Broadcast",
  symbol: "TBC",
  logoEmoji: "📻",
  priceUsd: 0.54,
  mcUsd: 740000,
  change24hPct: -11.61,
  holders: 1235,
  bondedPct: 100.0,
};

export const mockMessages: Message[] = [
  {
    id: 1,
    addr: "0x7f8a...b3A9",
    role: "holder",
    avatar: "🐸",
    text: "Hi! What do you think about liquidity post listing?",
    ts: Date.now() - 1000 * 60 * 2,
    reactions: { "👍": 6, "🔥": 2 },
    likes: 6,
  },
  {
    id: 2,
    addr: "0xAdmin...1CE0",
    role: "mod",
    avatar: "🛡️",
    text: "AMA scheduled for tomorrow, 20:00 EET.",
    ts: Date.now() - 1000 * 60 * 5,
    reactions: { "❤️": 3 },
    likes: 3,
  },
  {
    id: 3,
    addr: "0xdev...F00D",
    role: "team",
    avatar: "🧠",
    text: "Team: Added $120,000 to LP. Contract is renounced. Check the explorer.",
    ts: Date.now() - 1000 * 60 * 9,
    reactions: { "🚀": 7 },
    likes: 7,
  },
  {
    id: 4,
    addr: "0x84c...99ad",
    role: "holder",
    avatar: "🧸",
    text: "Bought another 0.42 ETH worth — bullish for the weekend announcement.",
    ts: Date.now() - 1000 * 60 * 12,
    reactions: {},
    likes: 0,
  },
  {
    id: 5,
    addr: "0xnew...0abc",
    role: "system",
    avatar: "",
    text: "Joined (holder)",
    ts: Date.now() - 1000 * 60 * 30,
    system: true,
    reactions: {},
    likes: 0,
  },
];
